name: Remove files and calling Batch file

on:
  push:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: msbuild

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Display the path
      run: echo ${{ github.workspace }}
      
    - name: Remove the old files
      run: |
        Remove-Item -path ${{ github.workspace }}\Scripts\msbuild-pipeline.txt
        Remove-Item -path ${{ github.workspace }}\README.md
        
    - name: Calling Batch file
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        echo "Running Batch file"
        ./Scripts/echo.bat
